__author__ = 'keleigong'

SM_step2 = [
    "allocation",
    "allocations",
    "Ariba",
    "assessment",
    "assessments",
    "audit",
    "audits",
    "award",
    "awards",
    "code",
    "codes",
    "conduct",
    "contract",
    "contracts",
    "database",
    "diversities",
    "diversity",
    "EDI",
    "EICC",
    "Electronic Industry Citizenship Coalition",
    "eprocurement",
    "e-procurement",
    "ERP",
    "esourcing",
    "e-sourcing",
    "evaluation",
    "expectation",
    "expectations",
    "guide",
    "guideline",
    "guidelines",
    "guides",
    "list",
    "lists",
    "measurement",
    "measurements",
    "noncompliance",
    "noncompliances",
    "Oracle",
    "policies",
    "policy",
    "portal",
    "preferred supplier",
    "preferred suppliers",
    "procurement",
    "procurements",
    "Procure-to-Pay",
    "registration",
    "requirement",
    "requirements",
    "SAP",
    "scorecard",
    "scorecards",
    "selection",
    "selections",
    "spend",
    "spends",
    "supplier of the year",
    "supply chain risk",
    "term and condition",
    "terminate",
    "terminates",
    "terms and conditions",
    "tracking",
    "trackings",
    "train",
    "training",
    "trainings",
    "verification",
    "verifications",
    "zero tolerance"
]

SS_step2 = [
    "allocation",
    "allocations",
    "Ariba",
    "assessment",
    "assessments",
    "audit",
    "audits",
    "award",
    "awards",
    "capacities",
    "capacity",
    "code",
    "code of conduct",
    "codes",
    "collaborate",
    "collaborates",
    "collaboration",
    "collaborations",
    "conduct",
    "conducts",
    "continuity",
    "contract",
    "contracts",
    "cooperate",
    "cooperates",
    "cooperations",
    "cross function",
    "cross functional",
    "Cross-functional",
    "development",
    "developments",
    "diversities",
    "diversity",
    "EDI",
    "EICC",
    "Electronic Industry Citizenship Coalition",
    "Enterprise Resource Planning",
    "eprocurement",
    "e-procurement",
    "ERP",
    "esourcing",
    "e-sourcing",
    "evaluation",
    "evaluations",
    "expectation",
    "expectations",
    "guideline",
    "improvement",
    "improvements",
    "key suppliers",
    "key vendors",
    "local",
    "long term",
    "Long-term",
    "management",
    "managements",
    "measurement",
    "measurements",
    "optimization",
    "optimizations",
    "optimizations",
    "Oracle",
    "policies",
    "policy",
    "portal",
    "preferred suppliers",
    "preferred vendors",
    "procurement",
    "Procure-to-Pay",
    "requirement",
    "requirements",
    "responsible procurement",
    "responsible sourcing",
    "risk",
    "SAP",
    "scorecard",
    "scorecards",
    "scorecards",
    "segmentation",
    "segmentations",
    "selection",
    "sourcing",
    "strategic",
    "strategies",
    "strategy",
    "summit",
    "summits",
    "supplies",
    "sustainability",
    "sustainable",
    "system",
    "systems",
    "team",
    "team",
    "term and condition",
    "terms and conditions",
    "tracking",
    "trackings",
    "training",
    "verification",
    "verifications"
]

CM_step2 = [
    "allocation",
    "allocations",
    "analytic",
    "analytics",
    "Ariba",
    "Beroe",
    "capabilities",
    "capability",
    "capacities",
    "capacity",
    "categories",
    "category",
    "collaboration",
    "collaborations",
    "commodities",
    "commodity",
    "cost model",
    "cost models",
    "cross-functional",
    "demand",
    "demands",
    "engagement",
    "engagements",
    "Enterprise Resource Planning",
    "ERP",
    "estimate",
    "estimated",
    "estimates",
    "estimation",
    "feedback",
    "feedbacks",
    "forecast",
    "forecasting",
    "integrate",
    "integrates",
    "integration",
    "intelligence",
    "intelligences",
    "list",
    "lists",
    "long term",
    "long-term",
    "management",
    "managements",
    "market analyses",
    "market analysis",
    "optimization",
    "optimizations",
    "optimize",
    "optimized",
    "optimizes",
    "Oracle",
    "real time",
    "real-time",
    "requirement",
    "requirements",
    "risk",
    "risks",
    "SAP",
    "scorecard",
    "scorecards",
    "segmentation",
    "segmentations",
    "sharing",
    "supply chain",
    "supply market",
    "supply markets",
    "team",
    "teams",
    "transparency",
    "transparent"
]

SRM_step2 = [
    "award",
    "awards",
    "agreement",
    "agreements",
    "beneficial",
    "benefit",
    "benefits",
    "code",
    "code of conduct",
    "codes",
    "collaborate",
    "collaborates",
    "collaboration",
    "commitment",
    "commitments",
    "communication",
    "communications",
    "conduct",
    "conducts",
    "conference",
    "conferences",
    "continuity",
    "continuous",
    "cooperate",
    "cooperates",
    "cooperation",
    "cooperative",
    "cross function",
    "cross-functional",
    "development",
    "developments",
    "expectation",
    "expectations",
    "fair",
    "feedback",
    "feedbacks",
    "global",
    "Global sourcing",
    "improvement",
    "improvements",
    "information sharing",
    "integrate",
    "integration",
    "interaction",
    "interactions",
    "list",
    "long term",
    "real time",
    "real-time",
    "long-term",
    "meeting",
    "meetins",
    "mutual",
    "policies",
    "policy",
    "portal",
    "purchase",
    "relationship",
    "relationships",
    "requirement",
    "requirements",
    "sharing",
    "SRM",
    "summit",
    "summits",
    "talent",
    "team",
    "teams",
    "training",
    "trainings",
    "transparency",
    "transparent"
]

LHR_step2 = [
    "assessment",
    "assessments",
    "association",
    "audit",
    "audits",
    "Child labor",
    "child labors",
    "citizenship report",
    "code of conduct",
    "compliance",
    "compliances",
    "Corrective Action",
    "CSR report",
    "CSR reports",
    "discrimination",
    "EICC",
    "Electronic Industry Citizenship Coalition",
    "enforcement",
    "enforcements",
    "enformance",
    "factories",
    "factory",
    "fail",
    "fails",
    "Fair Labor Association",
    "FLA",
    "forced labor",
    "forced labors",
    "HEALTH and SAFETY",
    "HSE",
    "human tracking",
    "human trackings",
    "ILO",
    "independent",
    "International labor association",
    "labor",
    "Labor right",
    "labor rights",
    "labors",
    "management",
    "Minimum Wage",
    "minimum wages",
    "monitor",
    "NGO",
    "noncompliance",
    "non-compliance",
    "Non-governmental Organization",
    "reporting",
    "requires",
    "responsibilities",
    "responsibility",
    "Responsible sourcing",
    "Second tier",
    "second tier",
    "slavery",
    "social",
    "strike",
    "strikes",
    "sub tier",
    "subcontractor",
    "subtier",
    "sustainable supply chain",
    "terminate",
    "terminated",
    "terminates",
    "termination",
    "tracking",
    "trafficking",
    "training",
    "worker",
    "worker right",
    "worker rights",
    "zero tolerance"
]

ES_step2 = [
    "assessment",
    "assessments",
    "audit",
    "audits",
    "carbon",
    "chemical",
    "chemicals",
    "closed-loop",
    "CO2",
    "code of conduct",
    "collaborate",
    "collaboration",
    "conflict material",
    "conflicts materials",
    "Corrective Action",
    "eco-friendly",
    "EICC",
    "Electronic Industry Citizenship Coalition",
    "emission",
    "emissions",
    "enforcement",
    "engage",
    "engagement",
    "engagements",
    "engages",
    "environment",
    "environmental",
    "green supplier",
    "green suppliers",
    "green supply",
    "HSE",
    "lifecycle",
    "lifecycles",
    "management",
    "monitor",
    "monitors",
    "noncompliance",
    "non-compliances",
    "recycle",
    "recycles",
    "reporting",
    "resource",
    "resources",
    "responsibilities",
    "responsibility",
    "Responsible sourcing",
    "Safety Environment",
    "scorecard",
    "scorecards",
    "Second tier",
    "sub contractors",
    "sub contractors",
    "sub tier",
    "subcontractor",
    "subcontractors",
    "sub-tier",
    "supply chain",
    "sustainability",
    "sustainable",
    "sustainable supply",
    "terminate",
    "terminates",
    "terminations",
    "tracking",
    "trackings",
    "training",
    "trainnings",
    "waste",
    "wastes",
    "zero tolrance"
]

SM_original = [
    "Ariba spend management",
    "Sourcing contract management system",
    "EDI",
    "EICC",
    "Electronic Industry Citizenship Coalition",
    "Enterprise Resource Planning",
    "e-procurement system",
    "ERP",
    "Supplier terminate",
    "Oracle",
    "Procurement",
    "Procurement team",
    "Procure-to-Pay system",
    "SAP",
    "Service Level Agreement",
    "Source approved vendor list",
    "Sourcing Process",
    "Spend management",
    "Spend analytics",
    "Supplier allocation",
    "Supplier assessment",
    "Supplier audit",
    "Supplier award",
    "Supplier code of conduct",
    "Supplier database",
    "Supplier diversity program",
    "Supplier evaluation",
    "Supplier expectation",
    "Supplier guideline",
    "Supplier list",
    "Supplier measurements",
    "Supplier portal",
    "Supplier purchase terms and conditions",
    "Supplier registration",
    "Supplier requirement",
    "Supplier scorecard",
    "Supplier selection",
    "Supplier tracking",
    "Supplier training",
    "Supply chain management",
    "Supply management system",
    "Vendor code of conduct",
    "Vendor expectation",
    "Vendor list",
    "Vendor management",
]

SS_original = [
    "Ariba spend management",
    "Continuous supplier improvement process",
    "Sourcing contract management system",
    "Cross-functional sourcing team",
    "EDI",
    "EICC",
    "Electronic Industry Citizenship Coalition",
    "Enterprise Resource Planning",
    "e-procurement system",
    "ERP",
    "Health Safety Security Environment",
    "Long-term sourcing strategy",
    "Oracle",
    "Procurement",
    "Procurement allocation",
    "Procure-to-Pay system",
    "SAP",
    "Service Level Agreement",
    "Sourcing Process",
    "Sourcing strategy",
    "Spend management",
    "Spend analytics",
    "Strategic sourcing",
    "Supplier  capacity",
    "Supplier allocation",
    "Supplier assessment",
    "Supplier audit",
    "Supplier award",
    "Supplier code of conduct",
    "Supplier collaboration",
    "Supplier continuity planning",
    "Supplier development plan",
    "Supplier diversity program",
    "Supplier evaluation",
    "Supplier expectation",
    "Supplier guideline",
    "Supplier measurements",
    "Supplier meeting",
    "Supplier optimization",
    "Supplier portal",
    "Supplier purchase terms and conditions",
    "Supplier requirement",
    "Supplier risk management",
    "Supplier scorecard",
    "Supplier segmentation",
    "Supplier selection",
    "Supplier tracking",
    "Supplier training",
    "Supplier verification",
    "Supply base capacity",
    "Supply chain management",
    "Supply management system",
    "Supply risk analysis",
    "Vendor code of conduct",
    "Vendor expectation",
    "Vendor management",
]

CM_original = [
    "Ariba spend management",
    "Beroe",
    "Category Management",
    "Long-term category strategy",
    "Category team",
    "Cross-functional category management team",
    "Cross-functional sourcing team",
    "Enterprise Resource Planning",
    "ERP",
    "Oracle",
    "SAP",
    "Spend management",
    "Spend analytics",
    "Supplier  capacity",
    "Supplier allocation",
    "Supplier collaboration",
    "Supplier feedback",
    "Supplier optimization",
    "Supplier requirement",
    "Supplier risk management",
    "Supplier scorecard",
    "Supplier segmentation",
    "Supply base capacity",
    "Supply chain management",
    "Supply management system",
    "Supply market analysis",
    "Supply market intelligence",
    "Supply risk analysis",
]

SRM_original = [
    "Continuous supplier improvement process",
    "Global sourcing",
    "Source approved vendor list",
    "SRM policy",
    "Supplier award",
    "Supplier code of conduct",
    "Supplier collaboration",
    "Supplier continuity planning",
    "Supplier development plan",
    "Supplier feedback",
    "Supplier list",
    "Supplier meeting",
    "Supplier portal",
    "Supplier purchase terms and conditions",
    "Supplier Relationship Management",
    "Supplier requirement",
    "Supply chain management",
    "Supply management system",
    "Talent management",
    "Vendor code of conduct",
    "Vendor expectation",
    "Vendor list",
    "Vendor management",
]

LHR_original = [
    "Second tier supplier audit",
    "Second tier supplier enforcement",
    "Child labor",
    "EICC",
    "Electronic Industry Citizenship Coalition",
    "Fair Labor Association",
    "Labor Right",
    "Minimum Wage",
    "Non-governmental Organization",
    "Supplier code of conduct",
    "Supplier enforcement program",
    "Supplier lawsuit",
    "Supplier tracking",
    "Supplier training",
    "CSR report",
    "Sustainability report",
    "Vendor code of conduct",
]

ES_original = [
    "Second tier supplier audit",
    "Second tier supplier enforcement",
    "EICC",
    "Electronic Industry Citizenship Coalition",
    "Green effort",
    "Product life cycle",
    "Supplier code of conduct",
    "Supplier enforcement program",
    "Supplier environmental engagement",
    "Supplier lawsuit",
    "Supplier tracking",
    "Supplier training",
    "CSR report",
    "Sustainability report",
    "Vendor code of conduct",
]